Story4Assign/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home.urls')),
    path('story6/', include('story6.urls')),
    path('story7/', include('story7.urls')),
    path('story8/', include('story8.urls')),
    path('secret/', include('secret.urls')),
    path('account/', include('django.contrib.auth.urls')),
    path('account/', include('account.urls')),

]

account/urls.py
from django.urls import path
from .views import UserRegisterView

app_name = 'account'

urlpatterns = [
    path('register/', UserRegisterView.as_view(), name='register'),
]

home/urls.py
from django.urls import path

from .views import showpelajaranView, pelajarandetailsView, deletepelajaranView
from . import views

app_name = 'home'

urlpatterns = [
    path('', views.index, name='index'),
    path('index/', views.index, name='index'),
    path('photo/', views.photo, name='photo'),
    path('story1/', views.story1, name='story1'),
    path('formpelajaran/', views.formpelajaran, name='formpelajaran'),
    path('showpelajaran/', showpelajaranView.as_view(), name='showpelajaran'),
    path('pelajarandetails/<int:pk>', pelajarandetailsView.as_view(), name='pelajarandetails'),
    path('pelajarandetails/<int:pk>/deletepelajaran', deletepelajaranView.as_view(), name='deletepelajaran'),
]

secret/urls.py
from django.urls import path
from . import views

app_name = 'secret'

urlpatterns = [
    path('', views.index, name='index'),
]

story6/urls.py
from django.urls import path

from .views import EventView, AddEventView, AddPesertaView
from . import views

app_name = 'story6'

urlpatterns = [
    path('', EventView.as_view(), name='index'),
    path('formpeserta/', AddPesertaView.as_view(), name='peserta'),
    path('formkegiatan/', AddEventView.as_view(), name='kegiatan'),

]

story7/urls.py
from django.urls import path
from . import views

app_name = 'story7'

urlpatterns = [
    path('', views.index, name='index'),
]

story8/urls.py
from django.urls import path
from . import views

app_name = 'story8'

urlpatterns = [
    path('', views.index, name='index'),
    path('data/', views.search, name='search'),
]

account/models.py
from django.db import models

# Create your models here.

home/models.py
from django.db import models

# Create your models here.
class pelajaran(models.Model):
    nama = models.CharField(max_length=30, default='nama pelajaran')
    dosen = models.CharField(max_length=75, default='me')
    sks = models.CharField(max_length=10, default='24')
    tahun = models.CharField(max_length=20, default='semester / tahun')
    deskripsi = models.TextField()
    ruang = models.CharField(max_length=20, default='where it be?')

secret/models.py
from django.db import models

# Create your models here.

story5/models.py
from django.db import models

# Create your models here.

story6/models.py
from django.db import models
from django.urls import reverse

# Create your models here.

class kegiatan(models.Model):
    namakegiatan = models.CharField(max_length=60, default='main')
    hari = models.CharField(max_length=60, default='besok')

    def __str__(self):
        return self.namakegiatan

    def get_absolute_url(self):
        return reverse('story6:index')
    
    
class peserta(models.Model):
    namapeserta = models.CharField(max_length=30)
    pengikut = models.ForeignKey(kegiatan, on_delete=models.CASCADE)

    def __str__(self):
        return self.namapeserta

    def get_absolute_url(self):
        return reverse('story6:index')
    

    

story7/models.py
from django.db import models

# Create your models here.

story8/models.py
from django.db import models

# Create your models here.

home/forms.py
from django import forms
from .models import pelajaran

class Pelajaranform(forms.ModelForm):
    class Meta:
        model = pelajaran
        fields = [
            'nama',
            'dosen',
            'sks',
            'tahun',
            'deskripsi',
            'ruang'
        ]
        widgets = {
            'nama': forms.TextInput(attrs={'class': 'form-control'}),
            'dosen': forms.TextInput(attrs={'class': 'form-control'}),
            'sks': forms.TextInput(attrs={'class': 'form-control'}),
            'tahun': forms.TextInput(attrs={'class': 'form-control'}),
            'deskripsi' : forms.Textarea(attrs={'class': 'form-control'}),
            'ruang': forms.TextInput(attrs={'class': 'form-control'})
        }

account/views.py
from django.shortcuts import render
from django.views import generic
from django.contrib.auth.forms import UserCreationForm
from django.urls import reverse_lazy

# Create your views here.
class UserRegisterView(generic.CreateView):
    form_class = UserCreationForm
    template_name = 'registration/registration.html'
    success_url = reverse_lazy('login')

home/views.py
from django.shortcuts import render
from django.views.generic import ListView, DetailView, DeleteView
from django.urls import reverse_lazy

from .models import pelajaran
from .forms import Pelajaranform

# Create your views here.

def index(request):
    return render(request, 'home/index.html')

def photo(request):
    return render(request, 'home/photo.html')

def story1(request):
    return render(request, 'home/story1.html')

def formpelajaran(request):
    my_form = Pelajaranform(request.POST or None)
    if my_form.is_valid():
        my_form.save()

    context = {
        'form': my_form
    }
    return render(request, 'home/formpelajaran.html', context)

class showpelajaranView(ListView):
    model = pelajaran
    template_name = 'home/showpelajaran.html'

class pelajarandetailsView(DetailView):
    model = pelajaran
    template_name = 'home/pelajarandetails.html'

class deletepelajaranView(DeleteView):
    model = pelajaran
    template_name = 'home/deletepelajaran.html'
    success_url = reverse_lazy('home:showpelajaran')

secret/views.py
from django.shortcuts import render

# Create your views here.
def index(request):
    return render(request, 'financialsecret/howtomakemoney.html')

story5/views.py
from django.shortcuts import render

# Create your views here.

story6/views.py
from django.shortcuts import render
from .models import kegiatan, peserta
from django.views.generic import ListView, CreateView

# Create your views here.
class EventView(ListView):
    context_object_name = 'daftar'
    template_name = 'story6/showkegiatan.html'
    queryset = kegiatan.objects.all()

    def get_context_data(self, **kwargs):
        context = super(EventView, self).get_context_data(**kwargs)
        context["peserta"] = peserta.objects.all() 
        return context
    
class AddPesertaView(CreateView):
    model = peserta
    template_name = 'story6/pesertaform.html'
    fields = '__all__'

class AddEventView(CreateView):
    model = kegiatan
    template_name = 'story6/kegiatanform.html'
    fields = '__all__'

story7/views.py
from django.shortcuts import render

# Create your views here.
def index(request):
    return render(request, 'story7/story7.html')

story8/views.py
from django.shortcuts import render
from django.http import JsonResponse
import requests
import json

# Create your views here.
def index(request):
    return render(request, 'story8/searchapi.html')

def search(request):
    searchword = request.GET['q']
    url_dest = 'https://www.googleapis.com/books/v1/volumes?q=' + searchword

    result = requests.get(url_dest)
    data = json.loads(result.content)
    return JsonResponse(data, safe=False)

home/templates/base.html
<!DOCTYPE html>
<html lang="en">

{% load static %}

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'home/style.css' %}">
    <link rel="stylesheet" href="{% static 'home/style1.css' %}">
    <link rel="stylesheet" href="{% static 'home/photo-page.css' %}">
    <link rel="stylesheet" href="{% static 'home/bootstrap.min.css' %}">
    <title>Theophilus Lukas</title>
</head>

<body>
    <div class="container-fluid">
        <div class="row">
            
            <div class="d-none d-md-block col-md-2 px-1 bg-dark position-fixed" id="sticky-sidebar"
                style="height: 100%; min-width: 140px; background-color: rgb(255, 164, 59); color:beige">
                <!-- <div class="sidbar-cont">


                    
                    <a class="sidbar-butt" href="/">
                        <img class="sidbar-lab" src="../static/svgs/home.svg" alt="home">
                    </a>

                    <a class="sidbar-butt" href="{% url 'home:story1' %}">
                        <img class="sidbar-lab" src="../static/svgs/account.svg" alt="me">
                    </a>

                    <a class="sidbar-butt" href="{% url 'home:photo' %}">
                        <img class="sidbar-lab" src="../static/svgs/camera.svg" alt="photos web">
                    </a>

                    <a class="sidbar-butt" href="{% url 'story7:index' %}">
                        <img class="sidbar-lab" src="../static/svgs/accordion.svg" alt="form">
                    </a>

                    <a class="sidbar-butt" href="{% url 'story8:index' %}">
                        <img class="sidbar-lab" src="../static/svgs/book.svg" alt="form">
                    </a>

                    {% if user.is_authenticated %}

                        <a class="sidbar-butt" href="{% url 'home:formpelajaran' %}">
                            <img class="sidbar-lab" src="../static/svgs/google-forms.svg" alt="form">                       
                        </a>

                        <a class="sidbar-butt" href="{% url 'home:showpelajaran' %}">
                            <img class="sidbar-lab" src="../static/svgs/folder.svg" alt="form">
                        </a>

                        <a class="sidbar-butt" href="{% url 'story6:index' %}">
                            <img class="sidbar-lab" src="../static/svgs/folder.svg" alt="form">
                        </a>

                        <a class="sidbar-butt" href="{% url 'logout' %}">
                            <h1 class="story9">Logout</h1>
                        </a>

                    {% else %}

                        <a class="sidbar-butt" href="{% url 'login' %}">
                            <h1 class="story9">Login</h1>
                        </a>

                    {% endif %}

                    <a class="sidbar-butt" href="{% url 'secret:index' %}">
                        <h1 class="story9">LIFE CHANGING STUFF</h1>
                    </a>

                    <a class="sidbar-butt" href="{% url 'account:register' %}">
                        <h1 class="story9">Register</h1>
                    </a>

                </div> -->
            </div>
            <div class="col offset-2" id="main">

                {% if user.is_authenticated %}

                    <h1 style="text-align: center; font-weight: 2em;background:rgb(49, 86, 206); color:aliceblue; height: 2em;">Hello, {{ user.username }}</h1>

                {% endif %}

                {% block content %}
                {% endblock %}

            </div>
        </div>
    </div>



</body>

home/templates/home/index.html
{% extends 'base.html' %}

{% block content %}
<div class="intro-flex">

    <div class="front-image" id="top"></div>

    <div class="intro">
        <br><br>
        <h1 class="top-name">
            THEOPHILUS
            <br>LUKAS
        </h1>
        <h3 class="institution">
            Universitas Indonesia - Faculty of Computer Science
        </h3>
        <h3 class="location">
            Jakarta, Indonesia
        </h3>
        <p class="mini-desc">
            An aspiring web developer and a UI design enthusiast. Currently pursuing a degree in
            Computer
            Science in the
            University of Indonesia.
        </p>
        <h3 class="email">
            Theophilus.Lukas@ui.ac.id
        </h3>
        <br><br><br><br><br>
        <div class="soc-med">
            <a href="https://www.instagram.com/lukas.pictures/">
                <img src="../static/svgs/instagram.svg" alt="instagram" class="instagram">
            </a>
            <a href="https://www.facebook.com/profile.php?id=100005343438494">
                <img src="../static/svgs/facebook.svg" alt="facebook" class="facebook">
            </a>
            <a href="https://www.linkedin.com/in/theophilus-hotasi-07038a237/">
                <img src="../static/svgs/linkedin.svg" alt="linkedin" class="linkedin">
            </a>
            <a href="https://twitter.com/Legendary_Lukas">
                <img src="../static/svgs/twitter.svg" alt="twitter" class="twitter">
            </a>
            <a href="https://gitlab.com/Theophilus_Lukas">
                <img src="../static/svgs/github.svg" alt="github" class="github">
            </a>

        </div>
    </div>

</div>

<div class="page2">

    <div class="about-me-flex" id="self-desc">
        <h2 class="about-me-title">
            About<br>
            Me
        </h2>
        <p class="about-me-par">
            Born in January 2001, in Jakarta, Indonesia. Has been interested in computers since
            first grade.
            Started my programming journey in highschool when i entered the national programming competition.
            My first
            language was Pascal and C#.
            <br><br>
            Now, I mostly use Python and Java. working on projects with Django and Springboot.
        </p>
    </div>


    <div class="skill">

        <div class="lang-logo">
            <div class="langitems">
                <img src="../static/svgs/java.svg" alt="java" class="logo">
                <img src="../static/svgs/python.svg" alt="python" class="logo">
                <img src="../static/svgs/hashtag.svg" alt="c sharp" class="logo">
                <img src="../static/svgs/matlab-svgrepo-com.svg" alt="Photoshop" class="logo">
            </div>
            <div class="langitems">
                <img src="../static/svgs/django-svgrepo-com.svg" alt="Photoshop" class="logo">
                <img src="../static/svgs/node-svgrepo-com.svg" alt="Photoshop" class="logo">
                <img src="../static/svgs/react-svgrepo-com.svg" alt="Photoshop" class="logo">
                <img src="../static/svgs/spring-boot-svgrepo-com.svg" alt="Photoshop" class="logo">
                <img src="../static/svgs/pgsql-svgrepo-com.svg" alt="Photoshop" class="logo">
            </div>
            <div class="langitems">
                <img src="../static/svgs/css-3.svg" alt="css" class="logo">
                <img src="../static/svgs/html-5.svg" alt="html" class="logo">
                <img src="../static/svgs/js-svgrepo-com.svg" alt="Photoshop" class="logo">
                <img src="../static/svgs/typescript-logo-svgrepo-com.svg" alt="Photoshop" class="logo">
            </div>
        </div>

        
        <h2 class="skill-title">
            Known<br>
            Languages<br>
            & Tools
        </h2>
    </div>

    <div class="side-me"></div>


    <div class="other-interest-flex">
        <h2 class="interest-title">
            Other<br>
            Skillsets<br>
            & Interests
        </h2>
        <div class="interest-logo">
            <img src="../static/svgs/lightroom.svg" alt="Lightroom" class="logo">
            <img src="../static/svgs/premier.svg" alt="Premiere" class="logo">
            <img src="../static/svgs/photoshop.svg" alt="Photoshop" class="logo">
        </div>
    </div>
</div>

<div id="education-link" class="education-panel">
    <div>
        <h2 class="education-title">
            Education
        </h2>
        <br>
        <ul class="edu-list" style="list-style-type:none;">
            <li>Universitas Indonesia</li>
            <li>SMAK 7 PENABUR</li>
            <li>SMPK 5 PENABUR</li>
            <li>SDK 4 PENABUR</li>
        </ul>

    </div>
    <br><br><br>
</div>
{% endblock %}

home/templates/home/story1.html
{% extends 'base.html' %}
   
{% block content %}
   <div class="top-name-1">
        <h1>LUKAS</h1>
        <div class="full-name-1">
            <h1>THEOPHILUS LUKAS</h1>
        </div>
        <div class="moto-1">
            <h2>~ Flectere si nequeo superos, Acheronta movebo ~</h2>
        </div>
        <div class="email-1">
            <h2>University of Indonesia - Faculty of Computer Science - 1906398332</h2>
            <h2>Theophilus.Lukas@ui.ac.id</h2>
        </div>
    </div>
    <img class="img-me-1" src="../static/img/obme.jpg" alt="Theophilus Lukas">
    <h2 class="in-memoriam-1">In Vitae Celebrationem</h2>
    <h2 class="years-active-1">
        2001 - 69420
    </h2>
    <div class="flex-row-1">
        <div class="about-me-box-1">
            <div class="about-me-1">
                <h2>About Me</h2>
            </div>
            <p class="about-me-par-1">
                Born in January, 2001 in the city of Jakarta, Indonesia into a family of five.
                <br>Currently pursuing a degree in Computer Science at the University of Indonesia.
            </p>
        </div>
        <div class="education-1">
            <div class="education-title-1">
                <h2> Education </h2>
            </div>
            <div class="education-content-1">
                <ul class="school-name-1">
                    <li>SDK 4 PENABUR</li>
                    <li>SMPK 5 PENABUR</li>
                    <li>SMAK 7 PENABUR</li>
                    <li>Universitas Indonesia</li>
                </ul>
                <dl class="school-year-1">
                    <dt>2007 - 2013</dt>
                    <dt>2013 - 2016</dt>
                    <dt>2016 - 2019</dt>
                    <dt>2019 - now</dt>
                </dl>
            </div>
        </div>

    </div>
{% endblock %}

secret/templates/financialsecret/howtomakemoney.html
<!DOCTYPE html>


<html>
{% load static %}

    <head>
        <link rel="stylesheet" href="{% static 'financialsecret/money.css' %}">
    </head>
    <body>

    {% if user.is_authenticated %}

    
        <h1 class="titleofmoney"> LIFE CHANGING STUFF </h1>

    <div class="wrapper">

        <h2 class="titleofmoney">A guide on how to WIN the game of LIFE, by the opportunistic Entrepreneur Yosua Hutagalung</h2>
        <iframe width="1280" height="720" class="video"
            src="https://www.youtube.com/embed/xFaEG-eTPxs">
        </iframe>

        <h2 class="titleofmoney">A journey through true beauty to find the divine artform, by the visionary Artist Lukas (myself)</h2>
        <iframe width="1280" height="720" class="video"
            src="https://www.youtube.com/embed/F3rTfNgO-74">
        </iframe>

        <h2 class="titleofmoney">A path to auditorial and spiritual perfection, by the soothing Audiophile Samuel Sharon</h2>
        <iframe width="1280" height="720" class="video"
            src="https://www.youtube.com/embed/7EQP6SyfYSE">
        </iframe>

        <h2 class="titleofmoney">And a collection of music that transcends divinity of human nature, by me</h2>
        <div class="spotify video" style="width: 1500px">
            
            <iframe 
                src="https://open.spotify.com/embed/playlist/5WCRS6MD8odFUVfykRH3ov" 
                width="300" height="380" frameborder="0" allowtransparency="true" 
                allow="encrypted-media">
            </iframe>
            
            <iframe 
                src="https://open.spotify.com/embed/playlist/4rP2v2Hbt6GeiU9wiNTZ5H" 
                width="300" height="380" frameborder="0" allowtransparency="true" 
                allow="encrypted-media">
            </iframe>
            
            <iframe 
                src="https://open.spotify.com/embed/playlist/3qQ27GfdMzI9MCpfZy2gIe" 
                width="300" height="380" frameborder="0" allowtransparency="true" 
                allow="encrypted-media">
            </iframe>

            <iframe 
                src="https://open.spotify.com/embed/playlist/5VItICXtFUzgoAmqy7QRFL" 
                width="300" height="380" frameborder="0" allowtransparency="true" 
                allow="encrypted-media">
            </iframe>

            <iframe 
                src="https://open.spotify.com/embed/playlist/3BxfZzSglFnRr34Ap8dYDy" 
                width="300" height="380" frameborder="0" allowtransparency="true" 
                allow="encrypted-media">
            </iframe>

        </div>

        
    </div> 

    {% else %}

        <h1 style="text-align: center;font-size: 6em">YOU NEED TO</h1>

        <a style="text-align: center; " href="{% url 'login' %}">
            <h1 style="font-size: 8em; border:5px solid white; padding:1em; background-color: white">Log in</h1>
        </a>

        <h1 style="text-align: center;font-size: 6em">to see some LIFE CHANGING videos</h1>

        

    {% endif %}

    <a style="margin-left: 47%" href="/">
        <img style="width: 60px; background: white; padding:1em; border-radius:2.7em" src="../static/svgs/home.svg" alt="home">
    </a>

    </body>
</html>

story6/templates/story6/kegiatanform.html
<html lang="en">

{% load static %}

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'story6/bootstrap.min.css' %}">
    <title>Form Kegiatan</title>
</head>

<body>
    <div class="text-center" style="margin-top: 300px">
        <h1 style="font-family: 'Roboto', sans-serif; font-size: 200px">KEGIATAN</h1>
        <form method="POST" style="font-size: 40px;"> {% csrf_token %}
            {{form.as_p}}
            <button>submit</button>
        </form>
        <a href="{% url 'story6:index' %}">
            <h2>Mundur Lur</h2>
        </a>
    </div>



</body>

</html>

story6/templates/story6/pesertaform.html
<html lang="en">

{% load static %}

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'story6/bootstrap.min.css' %}">
    <title>Form Peserta</title>
</head>

<body>

    <div class="text-center" style="margin-top: 300px">
        <h1 style="font-family: 'Roboto', sans-serif; font-size: 200px">PESERTA</h1>
        <form method="POST" style="font-size: 40px;"> {% csrf_token %}
            {{form.as_p}}
            <button>submit</button>
        </form>

        <a href="{% url 'story6:index' %}">
            <h2>Mundur Lur</h2>
        </a>
    </div>



</body>

</html>

story6/templates/story6/showkegiatan.html
<html lang="en">

{% load static %}

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'story6/bootstrap.min.css' %}">

    <title>Show Kegiatan</title>
</head>

<body>
    <div style="max-width: 1500px; margin-left: 30px; font-family: 'Roboto', sans-serif;">
        <h1 style="padding: 10px; font-size: 90px; max-width: 800px; margin-left: 50px; border-bottom : 10px solid black">KEGIATAN DAN PESERTA</h1>

        <div style="max-width: 800px; margin-left: 50px; font-family: 'Roboto', sans-serif;">
            {% for event in daftar %}

            <h1 style="max-width: 800px; font-size: 50px; font-family: 'Roboto', sans-serif; background-color:rgba(0, 76, 255, 0.322);border-left : 10px solid black; padding: 10px;">
                {{ event.namakegiatan }} - {{ event.hari }}</h1><br>

            <ul style="list-style-type: none">
                {% for member in peserta %}

                {% if member.pengikut == event %}
                <li>
                    <h2
                        style="padding: 0px; font-size: 40px; max-width: 300px; margin:0%; font-family: 'Roboto', sans-serif; border-bottom: 10px solid rgba(224, 224, 224, 0.671)">
                        {{ member.namapeserta }}</h2><br>
                </li>
                {% endif %}

                {% endfor %}
            </ul>

            {% endfor %}

        </div>



        <a href="{% url 'story6:kegiatan' %}">
            <h1
                style="background-color:rgb(214, 214, 214); padding: 10px; font-size: 30px; max-width: 300px; margin-left: 50px; font-family: 'Roboto', sans-serif; border-right : 10px solid black">
                Tambah Kegiatan</h1>
        </a>
        <a href="{% url 'story6:peserta' %}">
            <h1
                style="background-color:rgb(214, 214, 214); padding: 10px; font-size: 30px; max-width: 300px; margin-left: 50px; font-family: 'Roboto', sans-serif; border-right : 10px solid black">
                Tambah Peserta</h1>
        </a>
    </div>



</body>

</html>

story7/templates/story7/story7.html
<!DOCTYPE html>

{% load static %}

<html lang="en">
<head>
	<meta charset="UTF-8">
	<title>Accordion</title>
  <link rel="stylesheet" href="{% static 'story7/styleacc.css' %}">
  <link rel="stylesheet" href="//code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css">

  <script src="https://code.jquery.com/jquery-3.4.1.min.js"></script>
  <script src="https://code.jquery.com/jquery-1.12.4.js"></script>
  <script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>
	
</head>
<body>
<h1 class="judul">ACCORDIONS</h1>
<div class="wrapper">
  <div class="accordion_wrap accordion_1">
    <div class="accordion_header">
      Best Music Christmas Music
      <div class="RightFloat">
        <button value='up' class="singbutt">Up</button>
        <button value='down' class="singbutt">Down</button>
      </div>
    </div>
    <div class="accordion_body">
      <iframe src="https://open.spotify.com/embed/track/4ztOa2BmRDnZPrqrUD7gjN" width="300" height="230" frameborder="0" allowtransparency="true" allow="encrypted-media"></iframe>
    </div>
    
  </div>
  <div class="accordion_wrap accordion_2">
    <div class="accordion_header">
      Current Activity
      <div class="RightFloat">
        <button value='up' class="singbutt">Up</button>
        <button value='down' class="singbutt">Down</button>
      </div>
    </div>
    <div class="accordion_body">
       <p>Studying computer science in the University of Indonesia. Soon to be IISMA Awardee?? </p>
    </div>
    
  </div>
  <div class="accordion_wrap accordion_3">
    <div class="accordion_header">
      Organizational Experience
      <div class="RightFloat">
        <button value='up' class="singbutt">Up</button>
        <button value='down' class="singbutt">Down</button>
      </div>
    </div>
    <div class="accordion_body">
      <p>Worked with developers to make websites such as projectsaveus.herokuapp.com, with the intention of helping share information regarding the pandemic.
        Making a website to anonymously report academic misconduct in campus.
      </p>
    </div>
    
  </div>
  <div class="accordion_wrap accordion_4">
    <div class="accordion_header">
      Achievments
      <div class="RightFloat">
        <button value='up' class="singbutt">Up</button>
        <button value='down' class="singbutt">Down</button>
      </div>
    </div>
    <div class="accordion_body">
      <ul class="unordered">
        <li>
          3 Victories on Apex Legends with Mirage
        </li>
        <li>
          Gold 1 on Rainbow Six Siege
        </li>
        <li>
          Completed every raid on Destiny 2
        </li>
        <li>
          A cool vandal skin in Valorant
        </li>
      </ul>
    </div>
    
  </div>
</div>

<br><br>
<a href="{% url 'home:index' %}" class="singbutt-rev">Back to Main Page</a>
<br><br>

<div id="accordion" style="width:700px; margin-left: 33%">
  <h3>Identity</h3>
  <div>
    <p>
      issa me, lukas
    </p>
  </div>
  <h3>Current Activity</h3>
  <div>
    <p>
      Studying computer science in the University of Indonesia. Soon to be IISMA Awardee??
    </p>
  </div>
  <h3>Organizational Experience</h3>
  <div>
    <p>
      Worked with developers to make websites such as projectsaveus.herokuapp.com, with the intention of helping share information regarding the pandemic.
      Making a website to anonymously report academic misconduct in campus.
    </p>
  </div>
  <h3>Achievments</h3>
  <div>
    <ul>
      <li>
        3 Victories on Apex Legends with Mirage
      </li>
      <li>
        Gold 1 on Rainbow Six Siege
      </li>
      <li>
        Completed every raid on Destiny 2
      </li>
      <li>
        A cool vandal skin in Valorant
      </li>
    </ul>
  </div>
</div>
<br><br><br>


<script>
  $(document).ready(function(){
    $(".accordion_header").click(function(){
      if ($(this).hasClass("active")) {
        $(this).removeClass("active");
      } else {
        $(this).addClass("active"); 
      }
            
    });
  });

  function moveUp(item) {
    var prev = item.prev();
    if (prev.length == 0)
        return;
    prev.css('z-index', 999).css('position','relative').animate({ top: item.height() }, 250);
    item.css('z-index', 1000).css('position', 'relative').animate({ top: '-' + prev.height() }, 300, function () {
        prev.css('z-index', '').css('top', '').css('position', '');
        item.css('z-index', '').css('top', '').css('position', '');
        item.insertBefore(prev);
    });
}
function moveDown(item) {
    var next = item.next();
    if (next.length == 0)
        return;
    next.css('z-index', 999).css('position', 'relative').animate({ top: '-' + item.height() }, 250);
    item.css('z-index', 1000).css('position', 'relative').animate({ top: next.height() }, 300, function () {
        next.css('z-index', '').css('top', '').css('position', '');
        item.css('z-index', '').css('top', '').css('position', '');
        item.insertAfter(next);
    });
}

$('button').click(function() { 
    var btn = $(this);
    var val = btn.val();
    if (val == 'up')
        moveUp(btn.parents('.accordion_wrap'));
    else
        moveDown(btn.parents('.accordion_wrap'));
    
    $(".accordion_header").removeClass("active");
});
  
$( function() {
  $( "#accordion" ).accordion();
} );
</script>
</body>
</html>

templates/gogo.html
<!DOCTYPE html>
<html>
    <head>

    </head>
    <body>
        <h1>lukas keren</h1>
    </body>
</html>